updated rules

diff --git a/.github/workflows/add-reviewers.yml b/.github/workflows/add-reviewers.yml
--- a/.github/workflows/add-reviewers.yml
+++ b/.github/workflows/add-reviewers.yml
@@ -2,7 +2,7 @@ name: Add Reviewers on PR Events
 
 on:
   pull_request:
-    types: [opened, edited, synchronize]
+    types: [opened, edited, synchronize, reopened]
 
 jobs:
   add-reviewers:
@@ -32,16 +32,16 @@ jobs:
 
           # Check if all reviewers are collaborators
           for reviewer in $(echo "$FINAL_REVIEWERS" | jq -r '.[]'); do
-            # Check if the reviewer is a collaborator
-            response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
-              -H "Accept: application/vnd.github.v3+json" \
-              "https://api.github.com/repos/$REPO/collaborators/$reviewer")
+          # Check if the reviewer is a collaborator
+          #  response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+          #    -H "Accept: application/vnd.github.v3+json" \
+          #    "https://api.github.com/repos/$REPO/collaborators/$reviewer")
               
-            if [[ $(echo "$response" | jq -r '.message') == "Not Found" ]]; then
-              echo "Reviewer $reviewer is not a collaborator."
-              exit 1  # Fail the job if any reviewer is not a collaborator
-            fi
-          done
+          #  if [[ $(echo "$response" | jq -r '.message') == "Not Found" ]]; then
+          #    echo "Reviewer $reviewer is not a collaborator."
+          #    exit 1  # Fail the job if any reviewer is not a collaborator
+          #  fi
+          #done
 
           # Make API call to add reviewers
           response=$(curl -s -X POST \
