updated rules

diff --git a/.github/workflows/prod-deploy.yml b/.github/workflows/prod-deploy.yml
--- a/.github/workflows/prod-deploy.yml
+++ b/.github/workflows/prod-deploy.yml
@@ -32,21 +32,25 @@ jobs:
           # Extract requested reviewers
           requested_reviewers=$(echo "$response" | jq -r '.requested_reviewers | map(.login) | .[]')
           
+          # Debug: Print response and reviewers for troubleshooting
+          echo "Response: $response"
+          echo "Requested reviewers: $requested_reviewers"
+
           # Check if required reviewers are present
           required_reviewers=("pathania25" "manasa-telus" "ravicharan-nettyam")
           missing_reviewers=()
 
           for reviewer in "${required_reviewers[@]}"; do
-            if [[ ! " ${requested_reviewers[@]} " =~ " ${reviewer} " ]]; then
-              missing_reviewers+=("$reviewer")
-            fi
+          if ! echo "$requested_reviewers" | grep -q "$reviewer"; then
+            missing_reviewers+=("$reviewer")
+          fi
           done
 
           if [ ${#missing_reviewers[@]} -ne 0 ]; then
-            echo "The following required reviewers are missing: ${missing_reviewers[*]}"
-            exit 1  # Fail the job if any required reviewers are not present
+          echo "The following required reviewers are missing: ${missing_reviewers[*]}"
+          exit 1  # Fail the job if any required reviewers are not present
           else
-            echo "All required reviewers are present."
+          echo "All required reviewers are present."
           fi
 
   deploy:
